<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TestAjax\Module'                        => __DIR__ . '/Module.php',
    'TestAjax\Controller\SkeletonController' => __DIR__ . '/src/TestAjax/Controller/SkeletonController.php',
    'TestAjax\Model\TestEntity'              => __DIR__ . '/src/TestAjax/Model/TestEntity.php',
);